config/routes.rb
DssPortal::Application.routes.draw do
  resources :app_bookmarks
  resources :favorites
  resources :site
  
resources :favorites do
  collection do
    post 'reorder'
  end
end

resources :favorites do
  collection do
    post 'drag_create'
  end
end

resources :favorites do
  collection do
    post 'drag_destroy'
  end
end

  root :to => 'application#welcome'
  

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  attr_accessible :app_id, :position, :loginid, :is_bookmark, :name
  validates :position, :presence => true
  #validates :loginid, :presence => true
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  # GET /favorites
  # GET /favorites.json
  def index
    @favorites = Favorite.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @favorites }
    end
  end

  # GET /favorites/1
  # GET /favorites/1.json
  def show
    @favorite = Favorite.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @favorite }
    end
  end

  # GET /favorites/new
  # GET /favorites/new.json
  def new
    @favorite = Favorite.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @favorite }
    end
  end

  # GET /favorites/1/edit
  def edit
    @favorite = Favorite.find(params[:id])
  end

  # POST /favorites
  # POST /favorites.json
  def create
    @favorite = Favorite.new(params[:favorite])

    respond_to do |format|
      if @favorite.save
        format.html { redirect_to @favorite, notice: 'Favorite was successfully created.' }
        format.json { render json: @favorite, status: :created, location: @favorite }
      else
        format.html { render action: "new" }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /favorites/1
  # PUT /favorites/1.json
  def update
    @favorite = Favorite.find(params[:id])

    respond_to do |format|
      if @favorite.update_attributes(params[:favorite])
        format.html { redirect_to @favorite, notice: 'Favorite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.json
  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy

    respond_to do |format|
      format.html { redirect_to favorites_url }
      format.json { head :no_content }
    end
  end

  def reorder
    reorder_favorites(params[:favorites])
    render :json => {}
  end

  def drag_create

      #1) create favorite
      @favorite = Favorite.new
      @favorite.app_id = params[:app].chop.to_i
      @favorite.loginid = @current_user.loginid
      @favorite.position = 1
      @favorite.name = params[:name].to_s
	
      if (params[:app_type] == "book")
      	@favorite.is_bookmark = true
      else 
	@favorite.is_bookmark = false      
      end
      
      @favorite.save

      #2) update the favorite id in the position array  (initially that field held the app_id info, not the id of the favorite
      ordering = params[:favorites]
      fav_index = params[:favorites].index(params[:app])
      ordering[fav_index] = @favorite.id
   
     #3) trigger reorder code
	reorder_favorites(params[:favorites])
     #4) send new id back to client to update the id attr on the li element 
    render :json => {:new_id => @favorite.id, :old_id => params[:app]}
  end

  def drag_destroy
	@favorite = Favorite.find(params[:app])
	app_id = @favorite.app_id.to_s + "a"
	old_id = @favorite.id
	if (@favorite.is_bookmark)
	      	app_type = "book"
	else 
		app_type = "rm"     
	end	
    	@favorite.destroy
	reorder_favorites(params[:favorites])
	#send new id back to client to update the id attr on the li element 
	render :json => {:old_id => old_id, :app_id => app_id, :app_type => app_type}
  end

  def reorder_favorites( favorites = [] )
    @favorite_ids = favorites
    n = 0
    ActiveRecord::Base.transaction do
      @favorite_ids.each do |id|
        favorite = Favorite.find(id)
        favorite.position = n
        n += 1
        favorite.save
      end
    end
  end
   
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_form.html.erb
<%= form_for(@favorite) do |f| %>
  <% if @favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
      <% @favorite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :position %><br />
    <%= f.number_field :position %>
  </div>
  <div class="field">
    <%= f.label :app_id %><br />
    <%= f.number_field :app_id %>
  </div>
  <div class="field">
    <%= f.label :loginid %><br />
    <%= f.text_field :loginid %>
  </div>
  <div class="field">
    <%= f.label :is_bookmark %><br />
    <%= f.number_field :is_bookmark %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favorites/edit.html.erb
<h1>Editing favorite</h1>

<%= render 'form' %>

<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

app/views/favorites/index.html.erb
<h1>Listing favorites</h1>

<table>
  <tr>
    <th>Position</th>
    <th>App_id</th>
    <th>loginid</th>
    <th>is_bookmark</th>
    <ht>name</th>
   <th> </th>
    <th></th>
    <th></th>
  </tr>

<% @favorites.each do |favorite| %>
  <tr>
    <td><%= favorite.position %></td>
    <td><%= favorite.app_id %></td>
    <td><%= favorite.loginid %> </td>
    <td><%= favorite.is_bookmark %> </td>
    <td><%= favorite.name %> </td>
    <td><%= link_to 'Show', favorite %></td>
    <td><%= link_to 'Edit', edit_favorite_path(favorite) %></td>
    <td><%= link_to 'Destroy', favorite, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Favorite', new_favorite_path %>

app/views/favorites/new.html.erb
<h1>New favorite</h1>

<%= render 'form' %>

<%= link_to 'Back', favorites_path %>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Position:</b>
  <%= @favorite.position %>
</p>

<p>
  <b>app_id:</b>
  <%= @favorite.app_id %>
</p>
<p>
  <b>Loginid:</b>
  <%= @favorite.loginid %>
</p>

<p>
  <b>is_bookmark:</b>
  <%= @favorite.is_bookmark %>
</p>

<p>
  <b>name:</b>
  <%= @favorite.name %>
</p>

<%= link_to 'Edit', edit_favorite_path(@favorite) %> |
<%= link_to 'Back', favorites_path %>