config/routes.rb
DssPortal::Application.routes.draw do
  resources :app_bookmarks
  resources :favorites
  resources :site
  
resources :favorites do
  collection do
    post 'reorder'
  end
end

resources :favorites do
  collection do
    post 'drag_create'
  end
end

resources :favorites do
  collection do
    post 'drag_destroy'
  end
end

  root :to => 'application#welcome'
  

end

app/models/app_bookmark.rb
class AppBookmark < ActiveRecord::Base
  attr_accessible :description, :name, :url, :icon
  has_attached_file :icon
end

app/controllers/app_bookmarks_controller.rb
class AppBookmarksController < ApplicationController
  # GET /app_bookmarks
  # GET /app_bookmarks.json
  def index
    @app_bookmarks = AppBookmark.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @app_bookmarks }
    end
  end

  # GET /app_bookmarks/1
  # GET /app_bookmarks/1.json
  def show
    @app_bookmark = AppBookmark.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @app_bookmark }
    end
  end

  # GET /app_bookmarks/new
  # GET /app_bookmarks/new.json
  def new
    @app_bookmark = AppBookmark.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @app_bookmark }
    end
  end

  # GET /app_bookmarks/1/edit
  def edit
    @app_bookmark = AppBookmark.find(params[:id])
  end

  # POST /app_bookmarks
  # POST /app_bookmarks.json
  def create
    @app_bookmark = AppBookmark.new(params[:app_bookmark])

    respond_to do |format|
      if @app_bookmark.save
        format.html { redirect_to @app_bookmark, notice: 'App bookmark was successfully created.' }
        format.json { render json: @app_bookmark, status: :created, location: @app_bookmark }
      else
        format.html { render action: "new" }
        format.json { render json: @app_bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /app_bookmarks/1
  # PUT /app_bookmarks/1.json
  def update
    @app_bookmark = AppBookmark.find(params[:id])

    respond_to do |format|
      if @app_bookmark.update_attributes(params[:app_bookmark])
        format.html { redirect_to @app_bookmark, notice: 'App bookmark was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @app_bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_bookmarks/1
  # DELETE /app_bookmarks/1.json
  def destroy
    @app_bookmark = AppBookmark.find(params[:id])
    @app_bookmark.destroy

    respond_to do |format|
      format.html { redirect_to app_bookmarks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/app_bookmarks_helper.rb
module AppBookmarksHelper
end

app/views/app_bookmarks/_form.html.erb
<%= form_for(@app_bookmark, :html => {:multipart => true}) do |f| %>
  <% if @app_bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app_bookmark.errors.count, "error") %> prohibited this app_bookmark from being saved:</h2>

      <ul>
      <% @app_bookmark.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
    
  <div class="field">
    <%= f.label :icon %><br />
    <%= f.file_field :icon %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/app_bookmarks/edit.html.erb
<h1>Editing app_bookmark</h1>

<%= render 'form' %>

<%= link_to 'Show', @app_bookmark %> |
<%= link_to 'Back', app_bookmarks_path %>

app/views/app_bookmarks/index.html.erb
<h1>Listing app_bookmarks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @app_bookmarks.each do |app_bookmark| %>
  <tr>
    <td><%= app_bookmark.name %></td>
    <td><%= app_bookmark.description %></td>
    <td><%= app_bookmark.url %></td>
    <td><%= link_to 'Show', app_bookmark %></td>
    <td><%= link_to 'Edit', edit_app_bookmark_path(app_bookmark) %></td>
    <td><%= link_to 'Destroy', app_bookmark, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New App bookmark', new_app_bookmark_path %>

app/views/app_bookmarks/new.html.erb
<h1>New app_bookmark</h1>

<%= render 'form' %>

<%= link_to 'Back', app_bookmarks_path %>

app/views/app_bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @app_bookmark.name %>
</p>

<p>
  <b>Description:</b>
  <%= @app_bookmark.description %>
</p>

<p>
  <b>Url:</b>
  <%= @app_bookmark.url %>
</p>
<p>
   <b>Icon:</b>
   <%= image_tag @app_bookmark.icon.url %>
</p>


<%= link_to 'Edit', edit_app_bookmark_path(@app_bookmark) %> |
<%= link_to 'Back', app_bookmarks_path %>